# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
